[programs.localnet]
soloha = "LHAPYTbqXFzkNxojt16Mx5gtAnnbhkZfMyLvU9xsKVe"

[programs.devnet]
soloha = "LHAPYTbqXFzkNxojt16Mx5gtAnnbhkZfMyLvU9xsKVe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
