name: Lint

on:
  push:
    branches:
      - "*"

env:
  NODE_VERSION: 16

jobs:
  lint_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        working-directory: ./app
        run: npm ci

      - name: ESLint & Prettier
        working-directory: ./app
        run: npm run lint

  lint_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        working-directory: ./discord
        run: npm ci

      - name: ESLint & Prettier
        working-directory: ./discord
        run: npm run lint
