name: Lint

on:
  push:
    branches:
      - "*"

env:
  NODE_VERSION: 16

jobs:
  lint_ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies

        run: npm ci

      - name: Lint
        run: npm run lint:app && npm run lint:discord

      - name: Format Check
        run: npm run fmt

  lint_program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Format
        working-directory: ./programs/soloha
        run: cargo fmt -- --check
